### ISSUE TITLE
"Fulcio&Rekor E2E Tests Using Release / e2e tests using release" check is flaky.

### ISSUE THREAD

**Issue by var-sdk** [sigstore/scaffolding#354]
**Description**

This check seems to have a high flake rate. e.g. 

https://github.com/sigstore/scaffolding/actions/runs/3055060149/jobs/4927689097

**Comment by vaikas** [comment]
I haven't seen this flake lately (with the exception when we started testing with 1.25 or actual failures). I'll look into stripping out all non-essential parts (this was somehow a flake with installing knative-eventing, which we don't need).

**Comment by vaikas** [comment]
#366 will address this in two ways. Not testing older releases (which had flakes and had been fixed since) as well, as testing with the v0.4.6. By default even though we were testing with the v0.4.6 "install" script, it was still installing the 0.4.4 by default, so fixing that as well. One big difference between 0.4.4 -> 0.4.6 was that Fulcio was not being super happy:
https://github.com/sigstore/scaffolding/pull/316
https://github.com/sigstore/scaffolding/issues/298

**Comment by haydentherapper** [comment]
I'm going to close this as we haven't seen the flake in a while, and we addressed this in other PRs. @vaikas please reopen if not
