### ISSUE TITLE
Add TSA to TUF

### ISSUE THREAD

**Issue by vaikas** [sigstore/scaffolding#465]
**Description**

As discussed [here](https://github.com/sigstore/scaffolding/pull/464) we need to add TSA keys to TUF root.

**Comment by vaikas** [comment]
@haydentherapper I don't see a TSA in the root-signing, where would I look for an example for how this should look like?
https://github.com/sigstore/root-signing/tree/main/targets

**Comment by vaikas** [comment]
haha, so the ts_chain.pem will get added to the TUF root, not the public key that we create for it (for the signer like Rekor)? So, I'd create two targets in TUF, is there a naming preference for them? I reckon there's just two targets, both with TSA usage?

**Comment by haydentherapper** [comment]
It'll be all certificates from `ts_chain.pem`, each being PEM-encoded. The leaf certificate (the "TSA certificate") includes the public key. This is more like Fulcio than Rekor.

Oh, actually, we need to make one change. We need to pass in a certificate chain for the file signer, like what we did in Fulcio. Otherwise, it's going to generate a new in-memory certificate chain each time.

For naming, let's do `tsa_leaf.crt.pem`, `tsa_intermediate.crt.pem`, and `tsa_root.crt.pem` (with intermediate being optional potentially)

**Comment by haydentherapper** [comment]
So you'll need to generate the certificate chain once, like what was done for Fulcio. I'll go make the update to include the chain now

**Comment by vaikas** [comment]
For, naming, do you foresee there being more than 3 (where the hardcoding works fine)? Instead of say, tsa_[0,1,2,3] as per the index in the chain.

**Comment by haydentherapper** [comment]
Could we only number the intermediates? I'd prefer the leaf and root be easily discoverable, so maybe tsa_intermediate_0, tsa_intermediate_1, etc, where 0 issued the leaf and all the way down to the root

**Comment by vaikas** [comment]
tsa_root.crt.pem
tsa_intermediate_1.crt.pem
tsa_intermediate_0.crt.pem
tsa_leaf.crt.pem

Like that?

**Comment by haydentherapper** [comment]
LGTM!

**Comment by vaikas** [comment]
@haydentherapper just one clarifying question. When you said usage is `tsa` should it really be `Tsa` or `TSA` to match other capitalizations? Like Fulcio and Rekor and CTFE?

**Comment by haydentherapper** [comment]
Maybe we should just call it timestamp instead? Otherwise, all caps to match
