### ISSUE TITLE
`cgr.dev/chainguard/alpine-base` is no longer receiving updates

### ISSUE THREAD

**Issue by mattmoor** [sigstore/scaffolding#773]
**Description**

I noticed this is the default `ko` base image for this repo:
https://github.com/sigstore/scaffolding/blob/d21c412f3c2f95421413f43741c2e62c19241dfe/.ko.yaml#L2

While we haven't withdrawn this (we should) we are no longer updating this, and so it is accumulating vulnerabilities.

I believe this was just our rebuild of Alpine at "edge", but you could also switch to `wolfi-base` here (no pressure, I'm biased).

**Version**

HEAD

**Comment by haydentherapper** [comment]
Thanks Matt for noticing this - @pwelch, let’s chat more with the other oncallers about this next meeting. We recently updated the rekor and fulcio containers to the latest distroless base (cc @loosebazooka), so we should evaluate if we want to use that here too (easier to track vulns and updates if we are using the same base image for all projects) or wolfi or another base.

**Comment by mattmoor** [comment]
Yeah, I was assuming there were system deps motivating `alpine` (vs. a distroless-style `static` image).

**Comment by haydentherapper** [comment]
We noticed with rekor and fulcio that our previous choices weren’t necessary and we could go down to a static image, so we will want to look here and see if we can do the same. My guess is yes, since most are Go binaries without dependencies on libc or libssl.

**Comment by loosebazooka** [comment]
Yeah any static image works. Distroless or wolfi for static should be interchangeable so I have no opinion. We should start adding rudimentary scanning at the repo level though with grype or something. Lemme look into this.

**Comment by pwelch** [comment]
We chatted about it on the on-call meeting. No strong opinions on what we use. If Wolfi is an easy drop in replacement lets just switch to that.

**Comment by haydentherapper** [comment]
Sorry I wasn’t able to make the meeting. One concern is that we don’t have great automated testing. Correct me if I’m wrong, but with wolfi, we will be picking up a new base image more frequently. Obviously this is nice for reducing CVEs, but this means there is some risk of introducing bugs without good regression testing. 
Can we try a static distroless image for now, test it out, and then discuss more about how we can have better automated testing of container releases? This is something that would be a nice improvement for rekor and fulcio too.

**Comment by mattmoor** [comment]
Yeah, switch to a static image if you can.

**Comment by imjasonh** [comment]
> Sorry I wasn’t able to make the meeting. One concern is that we don’t have great automated testing. Correct me if I’m wrong, but with wolfi, we will be picking up a new base image more frequently. Obviously this is nice for reducing CVEs, but this means there is some risk of introducing bugs without good regression testing. Can we try a static distroless image for now, test it out, and then discuss more about how we can have better automated testing of container releases? This is something that would be a nice improvement for rekor and fulcio too.

By all means I think you should switch to a static base image if at all possible, since it will contain the absolute minimum necessary, and as a result have the least amount of change.

To your other point, just to clarify, wolfi-base is also not updated very often, since it also doesn't contain much -- just `apk`, `busybox`, `glibc`, and a few others, none of which get frequent updates. As of right now `wolfi-base` was last updated October 3, 13 days ago. By contrast, the official `alpine` image was updated September 28, only about a week longer. If update speed and breakages are a concern, since it sounds like you don't depend on much (if anything?) from the base image, wolfi-base would probably be totally fine for you. A static image would be even better, and I'm glad to see you're moving that direction.

One difference between wolfi-base and alpine-base is architecture support -- Wolfi only supports amd64 and arm64 today, while Alpine has support for 7 architectures (incl s390x, ppc64le, 32-bit arm, etc.). I'm not sure if that's a requirement for this repo or not, but Wolfi wouldn't be able to support that if it is.

Chainguard also provides an Alpine-based static image, `cgr.dev/chainguard/static` with support for those 7 architectures, a nonroot default user, and it contains ca-certs and little else. It was last updated September 27, when Alpine updated.

I'm mostly just dropping FYIs, not trying to persuade anybody about what to use. distroless/static is a great choice, and basically anything is better than alpine-base at this point 😄
